# $OpenBSD$

COMMENT =		diff JSON and JSON-like structures in Python

MODPY_EGG_VERSION =	1.2.0

DISTNAME =		jsondiff-${MODPY_EGG_VERSION}
PKGNAME =		py-${DISTNAME}

CATEGORIES =		textproc

HOMEPAGE =		https://github.com/ZoomerAnalytics/jsondiff

# MIT
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes
MODPY_PYTEST =		Yes

FLAVORS =		python3
FLAVOR ?=

.include <bsd.port.mk>
