# $OpenBSD$

COMMENT =		collection of helpers and mock objects for unit tests

MODPY_EGG_VERSION =	6.10.3

DISTNAME =		testfixtures-${MODPY_EGG_VERSION}
PKGNAME =		py-${DISTNAME}

CATEGORIES =		devel

HOMEPAGE =		https://github.com/Simplistix/testfixtures

# MIT
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes
MODPY_PYTEST =		Yes
MODPY_PYTEST_ARGS =	testfixtures

FLAVORS =		python3
FLAVOR ?=

.include <bsd.port.mk>
