# $OpenBSD$

COMMENT =	Manhole is in-process service that will accept unix domain

MODPY_EGG_VERSION =	1.6.0

DISTNAME =	manhole-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	pypi

HOMEPAGE =	https://github.com/ionelmc/python-manhole

# unknown license -> 'BSD 2-Clause License'
PERMIT_PACKAGE =	unknown license
PERMIT_DISTFILES =	unknown license

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes

FLAVORS =	python3
FLAVOR ?=

.include <bsd.port.mk>
