# $OpenBSD$

COMMENT =	Test automation helper for PyQt applications

MODPY_EGG_VERSION =	0.0.1

DISTNAME =		qtbot-${MODPY_EGG_VERSION}
PKGNAME =		py-${DISTNAME}

CATEGORIES =		x11 devel

HOMEPAGE =		https://github.com/boylea/qtbot

# MIT
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes

# Author didn't include tests
NO_TEST =		Yes

.include <bsd.port.mk>
