# $OpenBSD$

COMMENT =		command-line parsing library for Python

MODPY_EGG_VERSION =	1.4.0

DISTNAME =		argparse-${MODPY_EGG_VERSION}
PKGNAME =		py-${DISTNAME}

CATEGORIES =		devel

HOMEPAGE =		https://github.com/ThomasWaldmann/argparse/

# Python Software Foundation License
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes
MODPY_PYTEST =		Yes

FLAVORS =		python3
FLAVOR ?=

.include <bsd.port.mk>
