# $OpenBSD$

COMMENT =	Minimal bindings to GitHub's fork of cmark

MODPY_EGG_VERSION =	0.4.2

DISTNAME =	cmarkgfm-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	pypi

HOMEPAGE =	https://github.com/jonparrott/cmarkgfm

# license field not set, consider bugging module's author
PERMIT_PACKAGE =	unknown license
PERMIT_DISTFILES =	unknown license

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes

FLAVORS =	python3
FLAVOR ?=

.include <bsd.port.mk>
