# $OpenBSD$

COMMENT =		platform independent file lock in Python

MODPY_EGG_VERSION =	3.0.12

DISTNAME =	filelock-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	sysutils

HOMEPAGE =	https://github.com/benediktschmitt/py-filelock

# Unlicense
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes

FLAVORS =	python3
FLAVOR ?=

.include <bsd.port.mk>
