# $OpenBSD$

COMMENT =	ASGI specs, helper code, and adapters

MODPY_EGG_VERSION =	3.2.3

DISTNAME =	asgiref-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	www

HOMEPAGE =	http://github.com/django/asgiref/

MAINTAINER =	Wen Heping <wenheping2000@hotmail.com>

# BSD
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes
MODPY_VERSION =		${MODPY_DEFAULT_VERSION_3}
MODPY_PYTEST =		Yes

.include <bsd.port.mk>

