# $OpenBSD$

COMMENT =		create standalone executables from Python scripts

MODPY_EGG_VERSION =	6.0

DISTNAME =		cx_Freeze-${MODPY_EGG_VERSION}
PKGNAME =		py-${DISTNAME:L}

CATEGORIES =		sysutils

HOMEPAGE =		https://anthony-tuininga.github.io/cx_Freeze

# Python Software Foundation License
PERMIT_PACKAGE =	Yes

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes
MODPY_VERSION =		${MODPY_DEFAULT_VERSION_3}
MODPY_PYTEST =		Yes

.include <bsd.port.mk>
