# $OpenBSD$

COMMENT =	The most basic Text::Unidecode port

MODPY_EGG_VERSION =	1.3

DISTNAME =	text-unidecode-${MODPY_EGG_VERSION}
PKGNAME =	py-${DISTNAME}

CATEGORIES =	pypi

HOMEPAGE =	https://github.com/kmike/text-unidecode/

# unknown license -> 'Artistic License'
PERMIT_PACKAGE =	unknown license
PERMIT_DISTFILES =	unknown license

MODULES =		lang/python

MODPY_PI =		Yes
MODPY_SETUPTOOLS =	Yes

FLAVORS =	python3
FLAVOR ?=

.include <bsd.port.mk>
